### PR TITLE
add check for inline comments in config parsing

### PR DESCRIPTION
**Pull request by kumar003vinod**
As suggested with #1091, I propose this new PR.
Current config parsing treats anything after required config parameters as a comment. In this change, I parse the config line further to make sure that we only have comment text after the required configuration.
With this change assumed that `log_dest` `include_dir`, `bridge_protocol_version` and `auth_opt_*` config parameters do not have space in configuration value.

For example, according to old logic `max_connections 100 comment` configuration is valid, but with this change, we will throw an error and `max_connections 100 # comment` is valid.
```
Error: Invalid configuration (comment) found after 'max_connections' configuration value (100).
```

And added one minor fix where current parsing logic throws an error if some a comment line starts with space.
```
# this is a comment
 # this is another comment
```

Signed-off-by: Vinod Kumar <kumar003vinod@gmail.com>

- [ ] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you successfully run `make test` with your changes locally?
- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

### CODE REVIEW

**Comment by ralight** [comment]
I've been considering this for a while and I think that it is important not to break existing configs. It is possible that  `log_dest` `include_dir`, and `auth_opt_*` all have spaces in legitimate cases at the moment. That only leaves `tls_version`. I think it might be best to leave this until breaking changes in version 2.0.

**Comment by kumar003vinod** [comment]
Thanks for your input. If I remove the check for these config parameters, will it be good to go?
In this PR I also did not handle for `conf__parse_string`, because it also allows spaces in values, maybe we can come up with a better solution for these cases.

**Comment by ralight** [comment]
I think I'd prefer to leave it as is for now actually. There's too much aggravation for people if something breaks. Breaking changes in 2.0 could include a change in config file format to something more standard, which removes this issue.

**Comment by kumar003vinod** [comment]
Thanks, Roger. That makes perfect sense.

**Pull request closed without merging**
