### PR TITLE
fix SOCKS5 username\password set. fix SOCKS5 request

### PR DESCRIPTION
**Pull request by yzhivik**
- [ ] If you are contributing a new feature, is your work based off the develop branch?
- [ ] If you are contributing a bugfix, is your work based off the fixes branch?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `make test` with your changes locally?
- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

### CODE REVIEW

**Comment by ralight** [comment]
Hello, thank you for your contribution. It looks like this is a worthwhile thing to include, but needs some work first.

Please split the separate issues into separate commits.
Please fix the formatting style to match the existing code.
Please try to remove the duplicate code from the ipv4/ipv6/domain section where possible.
Please complete the list of checkboxes in the original PR comment.

**Comment by yzhivik** [comment]
@ralight Hello, fixed, please review

**Comment by ralight** [comment]
I've ended up squashing your work into a single commit to avoid the reformatting fixes (for future reference, it's better to replace the original commits in your PR than add new ones on the end). This is now merged through the command line, so I'm going to close this. Thanks very much for your work!

**Comment by yzhivik** [comment]
@ralight 
Thanks for pulling in!
I have local changes for:
1) PKCS12 container grinder (keys, certs and CAs)
2) Fix for TLS/SSL over proxy, lib tries to make secure connection with socks proxy instead of broker.
(This fix can be extended to distinguish or combine secured connection to broker or proxy or both)
WDYT?

**Pull request closed without merging**
