### PR TITLE
[#782] Add support for TLS SNI

### PR DESCRIPTION
**Pull request by ctron**
This fixes the missing support for TLS SNI in the client.

### CODE REVIEW

**Comment by karlp** [comment]
duplicate of https://github.com/eclipse/mosquitto/pull/626 (merged to next release branch) and also earlier #268 and #221

**Comment by ctron** [comment]
Awesome. So when will it be available. It seens the PRs are open for over a year.

**Comment by ralight** [comment]
The IP log has been submitted and approved, I just need to finish the release docs and get it reviewed. I'll be trying to do that tomorrow. In other words - it should be available in days.

**Comment by ralight** [comment]
This was fixed independently and is in 1.5.

**Pull request closed without merging**
