### PR TITLE
Upgrade/Set QoS for bridge connections.

### PR DESCRIPTION
**Pull request by peppo65**
Related to issue #203.
A boolean flag `upgrade_bridge_qos` has been added in configuration (default false).
QoS is then handled in a way similar to the more general case of `upgrade_outgoing_qos`, with the additional constraint that we are in a bridge context.

### CODE REVIEW

**Comment by peppo65** [comment]
Signed-off-by: Massimo Perrone <peppo65@gmail.com>

**Comment by ralight** [comment]
This looks ok, thank you. There are some changes I'd like to see before I can accept your work.

1. Please base this work off the `develop` branch, that's the place for new features.
2. You must meet the IP requirements for submissions - please see `CONTRIBUTING.md`.
3. There doesn't seem to be any need for so many commits, so please squash them into a single commit :)
4. Please consider adding documentation to the example config file `mosquitto.conf` and to `man/mosquitto.conf.8.xml` - particularly with regards to the difference between `upgrade_outgoing_qos` and `upgrade_bridge_qos`.
5. Add a changelog entry

The last two points aren't a deal breaker, I'm happy to add them myself.

**Comment by peppo65** [comment]
Hi Roger,

ok for the changes, sorry for the inconvenience.

Massimo


2016-07-05 23:20 GMT+02:00 Roger Light <notifications@github.com>:

**Comment by peppo65** [comment]
Pull request moved onto develop branch.

**Pull request closed without merging**
