### PR TITLE
add .editconfig file

### PR DESCRIPTION
**Pull request by liudf0716**
add .editconfig file to make mosquitto's code more readable in github

### CODE REVIEW

**Comment by karlp** [comment]
The whole poitn of using hard tabs for indenting is that indent size can then be personal preference.  This file config seems to try and overrride that to _your_ preference.

**Comment by liudf0716** [comment]
@karlp I dont think that's my personal favorite, if u read code in github, can u endure tab is 8 space?

**Comment by ralight** [comment]
I would be happy to accept this, but you can see that the PR doesn't pass the IP validation checks. Please try to resubmit, making sure you have signed the ECA and that the commits have the correct email address in them.

**Comment by liudf0716** [comment]
@ralight thanks!
I have signed ECA. In order to resubmit this PR, do I have to close this PR firstly and create another PR?

**Comment by PierreF** [comment]
@liudf0716 I don't find ECA for the email address used for the commit.
You need to sign the ECA with the same email that does the commit. Also you need to sign-off your commit (git commit -s).
You don't need to create a new PR, if you do a push force to update the commit, the ip-validation will re-run on this PR.

**Comment by ralight** [comment]
I'm closing this for now, if you'd still like this to be merged, you'll need to fix the errors as Pierre mentioned.

**Pull request closed without merging**
