### PR TITLE
Optimize networking related code.

### PR DESCRIPTION
**Pull request by michaeliu**
Optimize networking related code.

- Cleanup prolix networking code.
- Merge Async DNS and Sync DNS into network connect call, and all connection be handle by net__socket_connect_xxx (step1,2,3)
- Cleanup code for non-blocking connection and SSL connection establish.
- Fix Async connection with external loop(libevent) issue on some platform. (Close socket before delete it from epoll will cause unknown behaviors. I found it will faill into busy loop, use too high CPU time on MIPS platfrom: openwrt 15.05 kernel 3.18.29 with uClibc-0.9.33.2).
- make test has been run with/without ADNS enable. all passed. 

- [x] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `make test` with your changes locally?
- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

### CODE REVIEW

**Comment by michaeliu** [comment]
@ralight 

#1624 #1625 #1626 CI check failed due to leak of libcjson.

could you please check it and trigger CI check again?

**Comment by ralight** [comment]
This looks like a lot of good work, thanks for taking the time to work on it. As it stands though, you have lots of different changes all contained in the single commit. Could you please open separate pull requests to address the different changes you have made - i.e. the bullet points?

**Comment by michaeliu** [comment]
Hi Roger,

Thanks for reply and let me explain:

One of my project run MQTT by libmosquitto on embedded system.
It's single thread APP, and use libevent as event loop. so I decide to do something to make libmosquitto can be use truly on ASYNC way.

After go through the code I decide to rewrite networking code to make async methods and sync method to use the same low level functions.

I got issue on bridge test case since the async/sync networking functions used by bridge code too.
So I must rewrite networking code for bridge.

Then, to make sure async API work properly, SSL related code updated..

After code review by myself and testing with/without ADNS support and my own project.
It works well.

And the most important thing. I don't think it could be split into several PRs, since there are only one thing done: networking code optimized :-)

As I metioned in ISSUEs or PRs, I believe it's useful and will solve issues about bridge & external event loop.

Could you please review, and let me know if you need any comments or feedback about the changes.

Sorry for my bad english and let me know if anything make you confused.

**Comment by michaeliu** [comment]
@ralight 

Any comments?

Hope it's useful and could be accept :-)

**Comment by michaeliu** [comment]
Hi Roger @ralight,

It seems that you are busy for days.

The outline of changes is there and I think it's make code more clear after you check the code.

Let me know anything I can do when you get back on this.

**Comment by michaeliu** [comment]
I have rewrite the codes twice for make the changes will help others and I really hope it could be helpful.
But it seems that the code is not good enough... hmmm
forget it.

**Comment by karlp** [comment]
no, it's just that not everyone else is working at the same speed as you :)

**Comment by natcl** [comment]
Any updates on this ? We're having this exact issue where the bridge will block when our devices are offline...

**Comment by michaeliu** [comment]
> Any updates on this ? We're having this exact issue where the bridge will block when our devices are offline...

Hi there,

I had followed this months ago, the PR cannot accept since it has too many line of code (It's difficult to merge into mainline...)

And now I am not sure if I have enough time to rewrite it again to make it works with the latest version of code.

If you want to dive into code and need some clue/idea, you could email [me](michael.liu.point@gmail.com) and I'd like to share what I have done.

**Pull request closed without merging**
