### PR TITLE
fix #833

### LINKED ISSUE #833: broker 1.5 conf `use_identity_as_username true` TLS is broken
On a raspberry pi using raspbian package `Version: 1.5-0mosquitto1`, in the broker logfile, the logged username no longer matches the Common Name found in the client certificate.

output from: `sudo less /var/log/mosquitto/mosquitto.log`

```
1527190662: New client connected from 10.0.1.88 as 389IB4d3dWUllZpTLXUKcI (c1, k600, u'^E').
[...]
1527192380: New client connected from 10.0.1.51 as mosqpub/2404-rpi1 (c1, k60, u'^D').
```

the `u'^E'` and `u'^D'` in the log message above used to reflect the **Common Name** in the certificate, e.g. in output from `1.4.15` it is ` u'rpip3'`

```
1526905503: New client connected from 10.0.1.88 as 389IB4d3dWUllZpTLXUKcI (c1, k600, u'rpip3').
```

### PR DESCRIPTION
**Pull request by bricewge**
It partially revert the changes made in 9c6a5f3. But I used `ASN1_STRING_get0_data()` instead of the previous `ASN1_STRING_data()` because `openssl` say it is deprecated.

### CODE REVIEW

**Comment by bricewge** [comment]
Updated due to the remarks of @ptjm at https://github.com/eclipse/mosquitto/issues/833#issuecomment-404930482. It should work with openssl before version 1.1 and not broke when the CN contains nulls (https://wiki.openssl.org/index.php/Hostname_validation).

**Comment by toast-uz** [comment]
Note there is a comment as bellow in ChangeLog.txt on mosquitto v1.5.

```
- Support for openssl versions 1.0.0 and 1.0.1 has been removed as these are
  no longer supported by openssl.
```

What do you think about that?

**Comment by bricewge** [comment]
I wasn't aware of this comment.
@toast-uz Do you want me to update the PR to use `ASN1_STRING_get0_data()` instead so it only support `openssl 1.1` and higher?

**Comment by toast-uz** [comment]
Openssl 1.0.2 is still available. Is your patch needed and available with openssl 1.0.2?

**Comment by bricewge** [comment]
Yes it's needed since it fix a `mosquitto` bug and it should work with `openssl 1.0.2`.

**Comment by toast-uz** [comment]
OK. Understood this PR is valid. Then keep this PR and related issue.

**Comment by ralight** [comment]
Thanks for this PR, could you please sign the Eclipse Contributor Agreement and add a signed-off-by line to your commit message?

https://www.eclipse.org/legal/ECA.php

To add the line, do:

`git commit --amend -s`
`git push -f`

That should just update this PR.

**Comment by bricewge** [comment]
I just signed the ECA.

I didn't bothered to sign it at first because the first patch was trivial.

**Comment by ralight** [comment]
Lovely, thanks. I'll get to this later this afternoon.

**Comment by ralight** [comment]
I've merged this manually so it could go on the `fixes` branch rather than master, so I'm going to close this as merged. The commit is at the link below, thanks very much for your contribution.

https://github.com/eclipse/mosquitto/commit/2a3305a4a25ea7e7e33aecc535f04866c0f7cc9c

**Pull request closed without merging**
