### PR TITLE
Optimize networking code

### PR DESCRIPTION
**Pull request by michaeliu**
Signed-off-by: Michael Liu <michael.liu.point@gmail.com>

Optimize networking related code.

1. Cleanup prolix networking code.
2. Merge Async DNS and Sync DNS into network connect call, and all connection be handle by net__socket_connect_xxx (step1,2,3)
3. Cleanup code for non-blocking connection and SSL connection establish.
4. Fix potential memory leak.
5. Optimize code(deep loop).

PS:

R.I.P Dr Li wenliang, who passed away this morning and/or last night on the way of warning people about 2019-nCoV.

- [ ] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `make test` with your changes locally?
- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

### CODE REVIEW

**Comment by michaeliu** [comment]
Let me know if any details needed.
Hope it can be accept.

**Comment by michaeliu** [comment]
Fixme:
The patch discard properties for client lib connection when use try to use non-blocking method.
Check usage of mosquitto__post_connected() for more details.

I am not familiar with MQTT protocol, It may need keep a deep copy of properties and use it inside of  mosquitto__post_connected()?

**Comment by michaeliu** [comment]
@ralight  @PierreF  Could you review this? Thanks~

**Comment by ralight** [comment]
Could you please also base it on the `develop` branch.

**Comment by michaeliu** [comment]
> @michaeliu thank you for taking the time to write and submit this. I am definitely interested in the changes you've made here, but at the moment I think this is at least a number of pull requests in one. Do you think you could split it up into different changes as you've listed them to make it easier to review and test?

Okay， Iet me try this. I believe optimization code for deep loop and set host_ainfo could be a standalone PR. the code for networking changes(client and bridge) will still include lots of lines of code..


> Could you please also base it on the `develop` branch.

I will try this too.

**Comment by michaeliu** [comment]
> Fixme:
The patch discard properties for client lib connection when use try to use non-blocking method.
Check usage of mosquitto__post_connected() for more details.

I am not familiar with MQTT protocol, It may need keep a deep copy of properties and use it inside of mosquitto__post_connected()?

Any comment on this @ralight

**Comment by michaeliu** [comment]
@ralight  Hi Roger, I have split the PR into 4 PRs: #1621 #1624 #1625 #1626 .

Could you review them, thanks.

**Pull request closed without merging**
