### PR TITLE
Enhance bare makefile static library build

### PR DESCRIPTION
**Pull request by Lance0312**
This pull request includes two changes
1. Install the C static library
2. Build and install the CPP static library

### CODE REVIEW

**Comment by chelliwell** [comment]
Wouldn't it be better to have an additional/optional install target for the static library...? (I'm cross-compiling/installing, and don't want or need the static lib on my target)

**Comment by Lance0312** [comment]
Of course, I'll add the switch later today.

**Comment by ralight** [comment]
Thanks for this, I've now merged your work but have changed the behaviour a bit. I feel as though the best approach is actually to keep the two static libraries separate.

**Comment by Lance0312** [comment]
That works for me as well, thank you!

**Pull request merged**
