### PR TITLE
Adding http plugin interface

### PR DESCRIPTION
**Pull request by V-Gotwig**
Added a plugin interface to implement simple http server logic over libwebsockets, allowing both dynamic and static file request processing.

Cmake configuration:
cmake -DWITH_WEBSOCKETS=ON -DWITH_HTTP_PLUGIN=ON -DWITH_LIBMAGIC=ON .
  
WITH_WEBSOCKETS - libwebsockets, requred 
WITH_HTTP_PLUGIN - allow the plugin interface
WITH_LIBMAGIC - optionally add libmagic support for a better content mimetype recognition

Signed-off-by: Viktor Gotwig <viktor.gotwig@q-loud.de>

### CODE REVIEW

**Comment by Tifaifai** [comment]
Hello, 
Maybe add a documentation page / man page to your commit/PR.
THX

**Comment by toast-uz** [comment]
Could you explain the usecases and backgrounds on your PR?

**Comment by V-Gotwig** [comment]
Hello, thank you for interest. 
The main usecase was to add to our mosquitto powered IoT devices a lightweight Web-UI, eventually on requirement a REST API. Current mosquitto webserver implementation is fully statical and not well tested, failing to serve to the iOS clients, so a rework was needed.
I will try to write additional documentation next days, any feedback is welcome.

**Comment by toast-uz** [comment]
I'm not sure current mosquitto already supports webserver. Could you show me some related documents for that?

**Comment by V-Gotwig** [comment]
Please look for http_dir option at the mosquitto.conf(5) man page. Of course, mosquitto should be built with WITH_WEBSOCKETS=ON and run with a websocket listener set up.

**Comment by toast-uz** [comment]
Found. Thank you!

**Pull request closed without merging**
