### PR TITLE
Fix _POSIX_C_SOURCE : 199309L to 200809L

### PR DESCRIPTION
**Pull request by Tifaifai**
Signed-off-by: Tifaifai Maupiti <tifaifai.maupiti@gmail.com>

### CODE REVIEW

**Comment by ralight** [comment]
It's not going to make any difference here, but I suppose you're right that it should be more recent - thanks.

**Comment by Tifaifai** [comment]
For Travis CI Builds : 
```
gcc -c sub_client_output.c -o sub_client_output.o -Wall -ggdb -O2  -I. -I.. -I../lib -I../src -DVERSION="\"1.4.90\"" -std=c99 -DWITH_TLS -DWITH_TLS_PSK -DWITH_SOCKS
In file included from ../src/mosquitto_broker_internal.h:21:0,
                 from client_shared.h:21,
                 from sub_client_output.c:34:
../config.h:31:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200809L
 ^
sub_client_output.c:17:0: note: this is the location of the previous definition
 #define _POSIX_C_SOURCE 199309L
 ^
```

**Comment by ralight** [comment]
Gotcha - this is for your bridge branch (which I won't be looking at for version 1.5, sorry)

**Comment by Tifaifai** [comment]
Yes, but sub_client_output.c is a common file. Our branch bridge dynamic permit to test the different commit.
Okay for the information on v1.5 
Have You a public roadmap ? and after the different perspectives ? 
This discussion is for mosquitto-dev mailing list ! ;) ok

**Comment by karlp** [comment]
In general, you should try and make the commit comment say _why_ you were changing this.  Your commit comment here simply said the same thing as the diff, with no explanation for the change.

**Pull request merged**
