### PR TITLE
Fixes for bug [484761]

### PR DESCRIPTION
**Pull request by focusware-develop**
Previous pull request broke the build (some tests failing, because of a different return value when the authentication failed).

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=484761

**Comment by ralight** [comment]
The github issue for this bug is https://github.com/eclipse/mosquitto/issues/18

I'm afraid the fix you're proposing is invalid. If it was this easy it would have been fixed already. libwebsockets forbids calling libwebsocket_write/lws_write except from within the defined callback. It might work for you, but it's not the right thing to do.

The change to use CONNACK_REFUSED_BAD_USERNAME_PASSWORD is also incorrect, the spec defines this as for the situation when "the data in the user name or password is malformed".

**Comment by focusware-develop** [comment]
Ok, I understand your point. The problem with the current implementation is that the (SSL) socket connection is closed before the CONNACK is sent over the connection, and therefore it is not arriving at the client side.

Is there maybe a way to mark the connection as "to-be-closed a little later", instead of calling mqtt3_context_disconnect() directly? Or have the context disconnect function flush the buffers before closing the connection?

**Comment by focusware-develop** [comment]
About the CONNACK_REFUSED_BAD_USERNAME_PASSWORD change, you are absolutely right :-)
I only read the return code response, but the description indeed mentions "the data in the user name or password is malformed". Sorry about that.

**Comment by ralight** [comment]
Yes absolutely there is a way to do it - but I'm not entirely sure how. I think the route to the solution is to add an extra state in for the client which is "closing, but only after we've sent outgoing data".

**Pull request closed without merging**
