### PR TITLE
Documentation generation tweaks and improvements

### PR DESCRIPTION
**Pull request by karlp**
Variety of documentation updates.  All can be chosen individually if desired.  Changes to the autogenerated output only, no code changes.

- [x] If you are contributing a new feature, is your work based off the develop branch?
- [ ] If you are contributing a bugfix, is your work based off the fixes branch?
> (Could be considered a fix really, but it's currently based on develop)
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you successfully run `make test` with your changes locally?
> no, but I've run "make api" :)
- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

### CODE REVIEW

**Comment by karlp** [comment]
I started exposing all the MQTTv5 properties too, but it started to become a much bigger body of work :)

**Comment by karlp** [comment]
The CJSON build failures are a breakage in the travis setup to not have cjson, or the defaults to have cjson enabled, nothing related to this PR

**Comment by ralight** [comment]
Thanks, that's a tedious bit of editing you've done there :)

**Comment by karlp** [comment]
thanks and you're welcome!

**Pull request merged**
