### PR TITLE
Bridge dynamic by a publish on $SYS topic.

### PR DESCRIPTION
**Pull request by Tifaifai**
Hello,

Reopen #535 / #639 after rename a branch (dynamic-bridge-develop) : oups ;)
"Bridge dynamic by a publish on $SYS topic. #535 and #639"

Add allow_sys_update option to write on $SYS topic
Add Eclipse CLA signature validation.

In this PR, we submit a new functionality for the bridge.
Our commit propose to manage bridge dynamically by a publish message on $SYS topic.
This new functionality permit to create and delete bridges after the config file step.
More explainations on this functionnality in documentation or PR #535.

Our use case is IoT management with different brokers on different Embedded Systems.

This PR is functionnal for 3 branches available  our repository [tifaifai/mosquitto](https://github.com/Tifaifai/mosquitto): master, fixes, develop

Please evaluate.

Thanks to @karlp @kartben @toast-uz
Signed-off-by: Tifaifai Maupiti <tifaifai.maupiti@gmail.com>

### CODE REVIEW

**Comment by Tifaifai** [comment]
Hello,

After more than six months, this functionality works well.
For your information, we will present our work at an international conference (ANT 2018).

The 9th International Conference on Ambient Systems, Networks and Technologies
May 8-11, 2018, Porto, Portugal.

` Dynamic bridge generation for IoT data exchange via the MQTT protocol - 
Alexandre Schmitt, Florent Carlier, Valérie Renault - 
Le Mans University / Laboratoire Centre de Recherche en Education de Nantes (CREN), Avenue O. Messiaen, 72085 Le Mans, France `

Do you think (@ralight @toast-uz ) you have an deadline to include this feature in the master/develop branch?
This would be nice for a demonstration at the conference with the official version of mosquitto and to discuss with other speakers of mosquitto ;-)

Thank you for all
Signed-off-by: Tifaifai Maupiti tifaifai.maupiti@gmail.com

**Comment by toast-uz** [comment]
@Tifaifai thank you for your contributing and sorry for your long waiting.

Now committer team focuses on the next version 1.5 (coming soon) based on current develop branch with some critical fixes. Your PR will be considered on the next develop version 1.5.x . We appreciate if you can understand that our work perfectly depends on volunteers.

See also https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg01672.html .

**Comment by Tifaifai** [comment]
No problem, we understand that it takes time. We look forward to the start of the v1.5 branch. We also give a lot of time to follow the mosquito, it is a proof of our interest ;-) We continue to preach the quality of Mosquitto broker ! The main purpose of our intervention was to inform you about the international conference.

**Comment by cjmaynard** [comment]
I was asked to leave a comment here and a link back to issue #539 and then close that issue to track everything here, so this comment serves that purpose.

**Comment by Tifaifai** [comment]
For your information and good reading....

[https://doi.org/10.1016/j.procs.2018.04.016](Article in The 9th International Conference on Ambient Systems, Networks and Technologies ANT 2018)

**Comment by sakthivel-pvs** [comment]
Have created new enhancement PR ( #938 ) related this PR. 
@toast-uz has suggested to discuss that issue also in this PR. 

I'm looking for dynamic subscription of topics for existing bridge connection and whatever configs adding dynamically needs to be updated in config file as well. So that will not lose any configuration.

According to mosquitto which is better approach to implement dynamic bridging, Either reload config or #653 based implementation ? 

If dynamic bridging is there then it should support following things,
1. New bridge connection
3. Delete a bridge connection
3. Adding new topic to existing bridge connection and initiate subscribe
4. Deleting a topic from existing bridge connection and initiate unsubscribe

**Comment by ralight** [comment]
Sorry, this was closed by accident.

**Comment by jsaak** [comment]
Is there any news about this?
I need a different functionality (trigger bridge reconnect), but the fundamentals are the same.
We need to integrate a request-response style client into the broker, I guess. (in $SYS namespace)
So we can send more than SIGHUP, SIGUSR1 and SIGUSR2 commands to the broker.

I am maintaining a fork of mosquitto with this functionality, but it would be nice to have this feature upstream.

**Comment by nicola-lunghi** [comment]
Hi any news on this?

would be very useful for us as well

or at least a "configuration reload" command like nginx for example

/usr/sbin/nginx -s reload

Thanks
Nick

**Comment by Tifaifai** [comment]
`Data exchange with the MQTT protocol: Dynamic bridge Approach - Alexandre Schmitt, Florent Carlier, Valérie Renault - 2019 IEEE 89th Vehicular Technology Conference: VTC2019-Spring
28 April – 1 May 2019, Kuala Lumpur, Malaysia`

**Comment by alex-bermishev** [comment]
any updates on this issue?

**Comment by Tifaifai** [comment]
Hi,

The functionality only works until release 1.5.4
The issue needs to be updated to work with the latest releases of mosquitto.
@ralight, is it necessary for us to spend time making an update pacth compatible with the latest releases?

We are still particularly interested in taking this feature into account in the mosquitto project.
We believe that the hot modification of bridges, through publications, is an important step forward for mosquitto.

Thanks,
Tifaifai.

**Comment by hei-pa** [comment]
is there any progress on this topic?

**Comment by Tifaifai** [comment]
Check a new version on Bridge-Dynamic-1.6.9-DYN on my account ;)

**Comment by Tifaifai** [comment]
Hello,

After two and a half years (testing/update/real use case), we are back with the latest version of mosquitto with the Dynamic Bridge.

In this PR, we submit a new functionality for the bridge (mosquitto_bridge).
Our commit propose to manage bridge dynamically by a publish message on $SYS topic.
This new functionality permit to create and delete bridges after the config file step.

Take Bridge-Dynamic_1.6.10 (https://github.com/Tifaifai/mosquitto), this version use mosquitto 1.6.10 and payload support JSON Message to create/delete bridge.

@ralight , we'd be honored if you'd include this feature in your master branch.

Thank you
Tifaifai

**Comment by Tifaifai** [comment]
Hello,

After two and a half years (testing/update/real use case), we are back with the latest version of mosquitto with the Dynamic Bridge.

In this PR, we submit a new functionality for the bridge (mosquitto_bridge tool).
Our commit propose to manage bridge dynamically by a publish message on $SYS topic.
This new functionality permit to create and delete bridges after the config file step.

Take Bridge-Dynamic_1.6.12 (https://github.com/Tifaifai/mosquitto), this version use mosquitto 1.6.12 and payload support JSON Message to create/delete bridge.

@ralight , we'd be honored if you'd include this feature in your master branch.

Thank you
Tifaifai

**Comment by Tifaifai** [comment]
Close with new PR (https://github.com/eclipse/mosquitto/pull/1811), compatible with last release. (mosquitto 1.6.12).

**Pull request closed without merging**
