### PR TITLE
health check for Docker

### PR DESCRIPTION
**Pull request by simonmcnair**
This is my first ever commit, please be gentle.

This is adding a health check for Docker.

This is not my own work.  This is taken from https://github.com/SensorsIot/IOTstack/issues/415

This is added as per authorisation in this link https://github.com/SensorsIot/IOTstack/issues/415#issuecomment-932667190

"For the benefit of anyone reading this issue who would like to take the Mosquitto iotstack_healthcheck.sh script and either use it as-is or improve it and then propose a PR for Eclipse-Mosquitto, please go right ahead and do that"

Thank you for contributing your time to the Mosquitto project!

Before you go any further, please note that we cannot accept contributions if
you haven't signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php).
If you aren't able to do that, or just don't want to, please describe your bug
fix/feature change in an issue. For simple bug fixes it is can be just as easy
for us to be told about the problem and then go fix it directly.

Then please check the following list of things we ask for in your pull request:

- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
- [x] If you are contributing a new feature, is your work based off the develop branch?
- [ ] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you successfully run `make test` with your changes locally?

-----

### CODE REVIEW

**Comment by simonmcnair** [comment]
I just noticed the topic may be incorrect in healthcheck.sh. 
Shall I change
HEALTHCHECK_TOPIC="${HEALTHCHECK_TOPIC:-iotstack/mosquitto/healthcheck}"
to
HEALTHCHECK_TOPIC="${HEALTHCHECK_TOPIC:-mosquitto/healthcheck}"

?
Cheers

**Comment by Paraphraser** [comment]
Thank you for doing this!!

I was going to suggest that "iotstack" in the default topic might be inappropriate. If it were me submitting this, I'd change it as you suggest above where you wrote "I just noticed..."

You might also want to copy/paste words from [IOTstack/Mosquitto container-health-check](https://github.com/SensorsIot/IOTstack/blob/master/docs/Containers/Mosquitto.md#container-health-check) into the Mosquitto documentation so everyone understands the theory and the environment variables that let you tailor it.

> I wrote the IOTstack doco at the above link so you can use this as me giving you all the permission you might need to copy, paste and rewrite to suit.

Assuming your PR gets approved and becomes part of Mosquitto, can you please follow-up and also propose PRs to delete the health check from IOTstack Mosquitto (master, old-menu and experimental branches).

**Comment by simonmcnair** [comment]
> Thank you for doing this!!
> 
> I was going to suggest that "iotstack" in the default topic might be inappropriate. If it were me submitting this, I'd change it as you suggest above where you wrote "I just noticed..."
> 
> You might also want to copy/paste words from [IOTstack/Mosquitto container-health-check](https://github.com/SensorsIot/IOTstack/blob/master/docs/Containers/Mosquitto.md#container-health-check) into the Mosquitto documentation so everyone understands the theory and the environment variables that let you tailor it.
> 
> > I wrote the IOTstack doco at the above link so you can use this as me giving you all the permission you might need to copy, paste and rewrite to suit.
> 
> Assuming your PR gets approved and becomes part of Mosquitto, can you please follow-up and also propose PRs to delete the health check from IOTstack Mosquitto (master, old-menu and experimental branches).

Sorry, Had a high level look but don't know where to find the "Mosquitto documentation".  Is it in another repo ?  Cheers (sorry for the newb questions)

**Comment by ralight** [comment]
@simonmcnair Thank you for attempting your first commit here, and sorry for the delay replying.

I very much like the idea of this, however I have to be fairly conservative accepting changes and I think this would break

**Pull request closed without merging**
