### PR TITLE
Add is session present

### PR DESCRIPTION
**Pull request by bettio**
Add getter for session present flag to the API.

### CODE REVIEW

**Comment by karlp** [comment]
What's the usecase for this?

**Comment by bettio** [comment]
Session present flag is part of the MQTT 3.1.1 specification and mosquitto API already allows to request a persistent session, but the client needs to know if the present flag (that is sent from the server) has been set or not/if the persistent session is already there, so those changes allow to know that.

**Comment by bettio** [comment]
Does anybody knows why the CI fails? I can't reproduce that issue here.

**Comment by Tifaifai** [comment]
After merge of roger and connack story ;)
```
./08-tls-psk-pub.py
FAIL: Received incorrect connack.
Received: CONNACK, rl=2, res=0, rc=5
Expected: CONNACK, rl=2, res=0, rc=0
...
Traceback (most recent call last):
  File "./08-tls-psk-pub.py", line 47, in <module>
    sock = mosq_test.do_client_connect(connect_packet, connack_packet, port=1889, timeout=20)
  File "/home/travis/build/eclipse/mosquitto/test/mosq_test.py", line 75, in do_client_connect
    raise ValueError
ValueError
```

**Comment by bettio** [comment]
Any news here?

**Comment by ralight** [comment]
Thanks very much for this contribution, but I've decided to implement it in a different way. See 86ced4d98fbe244c35ccc6a248862f06a2089fd4 and ff79432364fd87827c81838ba7ac3e7e6dc780a3. Does that seem reasonable to you?

For interest, the problem with the test is that when libmosquitto is compiled, a linker script ensures that only certain functions are exposed. You'd not added your function to the linker script, so the C++ library couldn't see that function. If you were compiling on Windows/Mac then you wouldn't have seen this, it only affects *nix.

**Comment by bettio** [comment]
Thanks a lot, I'll close this pull request.

**Pull request closed without merging**
