### PR TITLE
added ExecReload=/bin/kill -HUP $MAINPID to systemd unit files

### PR DESCRIPTION
**Pull request by jsaak**
added ExecReload=/bin/kill -HUP $MAINPID to systemd unit files

### CODE REVIEW

**Comment by jelly** [comment]
LGTM, this is also what Arch ships with it's own systemd unit.

**Comment by jsaak** [comment]
Why closed? I do not get it.

**Comment by ralight** [comment]
This was by accident, sorry.

**Comment by ralight** [comment]
This is now fixed in https://github.com/eclipse/mosquitto/commit/e4db8707a65c366dc505e2498774aae63db66994

**Pull request closed without merging**
