### PR TITLE
Add missing sys/time.h include on client_shared.h

### PR DESCRIPTION
**Pull request by maxice8**
Required by more strict libcs like musl libc.

- [ ] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you successfully run `make test` with your changes locally?
- [ ] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

### CODE REVIEW

**Comment by ralight** [comment]
Thank you. Your fix is good for posix systems, but doesn't work on Windows, so I've made my own fix in 5c0c830229e70053b36323f1192540602b53ce41.

**Comment by maxice8** [comment]
Thank you, will make my life easier packaging mosquitto on Linux

**Comment by ralight** [comment]
I'm right now preparing 1.6.1 to help everyone with this problem.

**Comment by maxice8** [comment]
Thank you

**Pull request closed without merging**
