### PR TITLE
CMakeLists.txt: Also install mqtt_protocol.h header file, mimic the M…

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
…akefile

This fixes bugs such as:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951116

### CODE REVIEW

**Comment by karlp** [comment]
wouldnt' have been a problem if you were using the makefiles for linux, as recommended would it :)

**Comment by LocutusOfBorg** [comment]
@karlp thanks to the switch, I discovered a serious bug (for Debian standards at least), in Makefiles too :)

https://github.com/eclipse/mosquitto/commit/7a5c2d4da514e8729ed52b9c48b09c04e5dfb469

We were using embedded library even if explicitly disabled... Having a cmake build failure helped me discover that the Debian version was outdated, while the package always built fine with the embedded library.

I still think having two build systems is not an ideal solution, but unless you want to get rid of cmake entirely, fixing it seems the best thing to do :)

**Comment by LocutusOfBorg** [comment]
Btw the file has been never installed in Debian, even when it was Makefile only :)

**Comment by LocutusOfBorg** [comment]
@ralight ping please? :)

**Comment by ralight** [comment]
This has been fixed on the develop branch as part of other changes, which will be the next release anyway. Thanks for your report about this.

**Pull request closed without merging**
