### PR TITLE
Add 1.4.15 support for docker

### PR DESCRIPTION
**Pull request by odidev**
This PR is raised in accordance with #908 to enhance ```mosquitto``` for ```amr64v8``` architecture.

I have built and run this package at my end and can provide the required data for confirmation.
Please let me know if something else is required in this aspect.

Regards,

### CODE REVIEW

**Comment by odidev** [comment]
Ping @ralight @PierreF @karlp 
Hi Guys,
Request to have a look over proposed changes to enable support for ```arm64v8``` architecture.

Regards,

**Comment by Tifaifai** [comment]
Why don't use mosquitto 1.5.1 image ?? THX

**Comment by odidev** [comment]
Hi @Tifaifai 
Is ```mosquitto-1.5.1``` available for ```alpine``` distribution?

I think ```1.5.1``` is available via direct downloads only while RPM support is still at ```1.4.15```.
In addtion, I just cross-checked this:
https://mosquitto.org/download/
And this is mentioned as official support for **Eclipse-mosquitto**
- mosquitto-1.4.15.tar.gz (via Eclipse)

Please guide, if there is anything else which can be done to enable ```arm64v8``` support.

Regards,

**Comment by odidev** [comment]
Hi Guys,
Is there any update w.r.t. work in the direction of support for ARM64?

I would be happy to assist if something is required from my side to get this module in the official support list of ```arm64v8```

Regards,

**Comment by lag-linaro** [comment]
I can confirm that 1.4.15 is the latest version of Mosquitto available in the Alpine repos.

LGTM - please consider merging the PR.

**Comment by ralight** [comment]
A new dockerfile has been written which compiles from source, so there is no need to wait for Alpine to produce a package any more. 1.5.3 is no available. Thanks for your efforts on this. I'm closing it because it is no longer needed.

**Pull request closed without merging**
