### PR TITLE
Fix for persistent subscription issue #501.

### PR DESCRIPTION
**Pull request by PierreF**
This is an alternative fix to #532.

While looking at subs.c, I've found out that always search twice in the subs hierarchy using the very first token.
For example with sub_add/sub_add_recurse:
* sub__add will use the first token (" " or "$SYS") to find the subhier [link](https://github.com/eclipse/mosquitto/blob/d3239920d789a16cb9c54c598f4fc7d5ef03f2e9/src/subs.c#L461) 
* sub__add will call sub__add_recurse with the same token (e.g. not token->next)
* sub__add_recurse will once more use the first token to find the subhier [link](https://github.com/eclipse/mosquitto/blob/d3239920d789a16cb9c54c598f4fc7d5ef03f2e9/src/subs.c#L312)

This could be also seen with the sub__tree_print (signal USR2):
Without the fix:
```
1504888920: Socket error on client test, disconnecting.
     
       
        thetopic (test, 1)
    $SYS
      $SYS
        broker
```

With the fix:
```
1504888794: Socket error on client test, disconnecting.
     
      thetopic (test, 1)
    $SYS
      broker
```

Note that $SYS is present twice, also note that "thetopic" is indented on more level and an additional line (for the " " root prefix) is also present.

### CODE REVIEW

**Comment by toast-uz** [comment]
Great work!
I like this better than my PR #532 .

**Comment by toast-uz** [comment]
Confirmed this PR worked properly even after my PR #531 (Fix subs memory issue).

**Comment by ralight** [comment]
This needs looking at very carefully, I'm not sure the proposed solution is correct.

The reason for the duplicate "$SYS" and the empty "" is to enforce a separation between the "normal" tree and $SYS, so that subscribing to '#' does not subscribe to $SYS as well. This does need looking at more generally than just for $SYS.

Normally we wouldn't want to persist anything on $SYS, the only reason to do so is if there is a queued message for a user who has subscribed to it.

**Comment by PierreF** [comment]
There is indeed an issue during persistence :/
I've added 2 tests:
* One to test that pattern subscription like "#" does NOT match $SYS (it works)
* One to test that such pattern are persisted... which show that "$SYS/broker/uptime" is not persisted.

I'll look to this that.

**Comment by ralight** [comment]
There's definitely something not quite right with this, I'm having some inconsistencies when trying to load a persistence file that was created without this patch.

**Comment by ralight** [comment]
This was closed by accident, but I think I'm going to leave it closed unless there is an update to move it on.

**Pull request closed without merging**
