### PR TITLE
No pthread_cancel() on Android

### PR DESCRIPTION
**Pull request by dandrader**
- [x] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `make test` with your changes locally?
- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.

-----

pthread_cancel() is not available on Android

Thus mosquitto_loop_start() and mosquitto_loop_stop()  won't be available there (and mosquitto_connect_async() as a consequence).

### CODE REVIEW

**Comment by ralight** [comment]
Thanks for this Dan, I wasn't aware of that problem on Android. I hope you don't mind, I've fixed this in a slightly simpler fashion in the commit I've just pushed to `fixes`.

**Comment by dandrader** [comment]
Hi Robert,

Please correct me if I'm wrong, but If you unset WITH_THREADING then the mutexes won't be operational and therefore the API will no longer be thread-safe, right?

In my usage I'm running mosquitto_loop() in one thread, and the rest of the API in another one. Without calling mosquitto_threaded_set(... true) I get the obscure crashes mentioned in its documentation.

Disabling just the pthread_cancel usage, like I did in this patch, you lose the mosquitto_connect_async API but still keep using real mutexes to guard the internal data structures.

Will mosquitto_threaded_set(... true) still keep its promises without WITH_THREADING defined?

**Comment by ralight** [comment]
You make a good point, let's go with your solution instead.

**Comment by nihilus** [comment]
Actually bionic libc lacks pthread_cancel() as you've figured out; it requires stack unwinding and is to be considered a "hack" in most libc-implementations (no safe cancellation points), however for mosquitto I personally find waiting for pthread_join() more feasible than disable threading. Code based on the async-API won't be able to run on Android which is a pity.

**Pull request merged**
