### PR TITLE
In android ndk doesn't exist librt and libpthread

### PR DESCRIPTION
**Pull request by Arenoros**
I have problem with build mosqutto libs for android-ndk-16, it would be great if you merged this small fix 

- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
- [x] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `make test` with your changes locally?

-----

### CODE REVIEW

**Comment by karlp** [comment]
So, are you saying that pthreads is _available_ but not as a library?

**Comment by Arenoros** [comment]
> So, are you saying that pthreads is _available_ but not as a library?

Yes

**Comment by ralight** [comment]
Thank you. Could you please also add a signed-off-by line to your commit (with the same email address as you signed the ECA). You can do that with:

```
git commit --amend -s
git push -f
```

**Comment by Arenoros** [comment]
@ralight Done

**Comment by ralight** [comment]
Thank you!

**Pull request merged**
