### PR TITLE
Fix cmake not building correctly when WITH_CJSON=OFF

### LINKED ISSUE #2026: CJSON discovery fails even if WITH_CJSON=OFF
When building using **cmake**, and providing -DWITH_CJSON=OFF the cJson discovery process is still running and failing if I don't have cJson installed.

A simple fix in the main CMakeLists.txt will do the trick, surround the following block:

`FIND_PACKAGE(cJSON)`
`if (CJSON_FOUND)`
`    message(STATUS ${CJSON_FOUND})`
`else (CJSON_FOUND)`
`    message(STATUS "Optional dependency cJSON not found. Some features will be disabled.")`
`endif(CJSON_FOUND)`

with an :

`if (WITH_CJSON)`
`...`
`endif()`

That's all!

### PR DESCRIPTION
**Pull request by madhat1**
Thank you for contributing your time to the Mosquitto project!

Before you go any further, please note that we cannot accept contributions if
you haven't signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php).
If you aren't able to do that, or just don't want to, please describe your bug
fix/feature change in an issue. For simple bug fixes it is can be just as easy
for us to be told about the problem and then go fix it directly.

Then please check the following list of things we ask for in your pull request:

- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
- [ ] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you successfully run `make test` with your changes locally?
**It fails before and after my fix, I don't have cJson installed.**
-----

Fix cmake not building correctly when WITH_CJSON=OFF. 
In the main CMakeLists.txt, the cJson discovery process is executed regardless if WITH_CJSON is ON or OFF, this MR fixes that.

This fixes #2026

### CODE REVIEW

**Comment by ralight** [comment]
Thanks very much!

**Comment by madhat1** [comment]
No prob, my pleasure 😀.  Is this fix expected to be included in v2.0.6?

**Comment by ralight** [comment]
Yes, it's in `fixes` now which will become 2.0.6 in about a week.

**Comment by madhat1** [comment]
Awesome, keep up the good work mate!
BTW, the latest support for UDS in lib and broker is a big improvement, kudos for that!

**Pull request merged**
