### PR TITLE
Fix for set(CMAKE_MACOSX_RPATH 1) on Darwin systems

### PR DESCRIPTION
**Pull request by squjd**
Signed-off-by: Tony Bright <krakjn@gmail.com>

Thank you for contributing your time to the Mosquitto project!

Before you go any further, please note that we cannot accept contributions if
you haven't signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php).
If you aren't able to do that, or just don't want to, please describe your bug
fix/feature change in an issue. For simple bug fixes it is can be just as easy
for us to be told about the problem and then go fix it directly.

Then please check the following list of things we ask for in your pull request:

- [ ] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
- [ ] If you are contributing a new feature, is your work based off the develop branch?
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you successfully run `make test` with your changes locally?

-----

### CODE REVIEW

**Comment by squjd** [comment]
I don't have an eclipse account but this is a simple build fix for macos Big Sur. With these edits I was able to generate `libmosquitto` on a darwin based system.

**Comment by karlp** [comment]
What's the failure? rpath is not normally "just hard turn it on" ?

**Comment by squjd** [comment]
There is no failure. Just setting a variable in order to build `libmosquitto` on a macOS machine. Unless there is a better way?

**Comment by karlp** [comment]
So, what's the fix if there's no failure?

**Comment by squjd** [comment]
As someone who tried to build `libmosquitto` on macOS from a fresh pull down on the latest release, `CMake` was complaining that MACOSX_RPATH was not set preventing the build of the lib. The 3 line fix in this pull request resolves this issue.

**Comment by ralight** [comment]
I've looked into this, and I believe that the correct fix is to set `MACOSX_RPATH` to `ON`. This is now done by using `cmake_policy(SET CMP0042 NEW)`.

**Comment by squjd** [comment]
I noticed the build is based on **High Sierra** which is a bit dated circa 2017 and the toolchain is outdated.
This is from the Travis logs:  
```shell
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
  softwareupdate --all --install --force
If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

Thanks Roger for the insight, I will change the lines to reflect what you suggested.

**Comment by squjd** [comment]
Will start a new pull request with updated email that I have signed the ECA.

**Comment by karlp** [comment]
per cmake docs, CMP0042 is enabled by defualt, so where did your cmake come from if it's defualting off?

**Pull request closed without merging**
